### ISSUE TITLE
Subfolders

### ISSUE THREAD

**Issue by nithou** [CyberSkull/cbz.sh#1]
Hey man! Thanks for your script it does wonder! I'm trying to find a way to adjust it to seek subfolders, any idea how I could specify this as apparently it doesn't accept the /*/ for all subfolders

My mangas are stored in a folder/Source/Name-of-the-mange/ and I would like to run the script at least at the source level :/

**Comment by CyberSkull** [comment]
Try this:

```zsh
cd folder_holding_the_folder_of_sources
cbz.sh folder/*/*
```
That should get all the subdirectories of the directories inside `folder`. You may also want to look up zsh's `**` glob, which lets you do unlimited depth glob matching.

**Comment by CyberSkull** [comment]
The previous advice will result in too many extra subdirectories to the archive. `cbz.sh` uses `zip` which archives the whole path passed to it, so like zip, it should be run from in the same directory of the stuff you want to archive. So go ahead and do that if you don't mind having `folder/Source/Name-of-the-manga/` in every archive.

**Comment by nithou** [comment]
Seems to work indeed, now just getting zip errors when they want to verify it :D "zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)"

**Comment by nithou** [comment]
```
sudo bash cbz.sh */*
cbz.sh: line 113: ${(s[])string}: bad substitution
\e[0mArchiving: "\e[34m\e[4mMangaDex (EN)/Acid Town\e[39m\e[24m"
cbz.sh: line 113: ${(s[])string}: bad substitution
zip -mrTy9 "MangaDex (EN)/Acid Town.cbz" "MangaDex (EN)/Acid Town" -x "*.DS_Store" "*[Tt]humbs.db"\e[0m
  adding: MangaDex (EN)/Acid Town/ (stored 0%)
  adding: MangaDex (EN)/Acid Town/Dangerous Pleasure_Vol.1 Ch.2/ (stored 0%)
  adding: MangaDex (EN)/Acid Town/Dangerous Pleasure_Vol.1 Ch.2/018.jpeg (deflated 0%)
  adding: MangaDex (EN)/Acid Town/Dangerous Pleasure_Vol.1 Ch.2/008.jpeg (deflated 0%)
  [.....]
  adding: MangaDex (EN)/Acid Town/Tigrin_Vol.6 Ch.40/010.jpeg (deflated 4%)
sh: unzip: command not found
	zip warning: failed to get information from UnZip
sh: unzip: command not found
test of MangaDex (EN)/Acid Town.cbz FAILED

zip error: Zip file invalid, could not spawn unzip, or wrong unzip (original files unmodified)
\e[0m
```

**Comment by CyberSkull** [comment]
Can you give me the file name it chokes on?

**Comment by nithou** [comment]
Found, zip has been replaced by 7zip on my system (Synology), by removing the verification flag it works. Gonna see how I can adapt this to use 7zip

**Comment by CyberSkull** [comment]
Anyways, I threw together this quick and dirty script that will walk the 2nd level directories and zip the contents.
```zsh
#! /bin/zsh
start=${PWD}

#echo $@

for target in "$@"
do
	if [[ -e $target ]]	#exists
	then
		if [[ -d $target ]]	#directory
		then
			if [[ -r $target ]]	#readable
			then
				cd ${target}
				#echo "Directory is \"$(pwd)\"."
				#echo "I will do \"$(basename ${target})/*\""
				cbz.sh *
				cd ${start}
			else
				echo "Not readable: \"${target}\""
			fi	#-r
		else
			echo "Not a directory: \"${target}\""
		fi #-d
	else
		echo "Not found: \"${target}\""
	fi	#-e
done
```
[cbzdirs.sh.zip](https://github.com/CyberSkull/cbz.sh/files/11295013/cbzdirs.sh.zip)

Use it thusly: `cbzdirs.sh folder/*`.

**Comment by nithou** [comment]
Wow thank you so much!!!

**Comment by CyberSkull** [comment]
And now that I've published that I've thought of a probably better way to do it. Maybe.
